### ISSUE TITLE
How to play with guardian?

### ISSUE THREAD

**Issue by AdoHe** [cloudfoundry-incubator/guardian#1]
FYI. Hi guys, I am wondering would you please document how to play with guardian?

**Comment by goonzoid** [comment]
Hi @AdoHe. You're right that the README could do with some work!

We'll try to get to this soon. We'd love to make guardian easier for people to hack on!

**Comment by AdoHe** [comment]
@goonzoid you guys did real amazing work, I am learning this project, hope I can make some contribution.

**Comment by julz** [comment]
Hey @AdoHe, thanks! (as you may've noticed :)) we've had to focus our attention on some final garden-linux stories in the last couple weeks to support the switchover to [Diego](http://github.com/cloudfoundry-incubator/diego) so we've been a bit distracted from Guardian. We've created [a story](https://www.pivotaltracker.com/story/show/105403348) in our tracker to properly flesh out the README on this repo to help folks get started contributing, you can see that story [here](https://www.pivotaltracker.com/story/show/105403348) and we'll also post here when it's done. Thanks again for your interest in Guardian!

**Comment by AdoHe** [comment]
@julz Thanks very much.

**Comment by luan** [comment]
Hi @AdoHe,

We just updated the https://github.com/cloudfoundry-incubator/guardian/blob/master/README.md with instructions on how to get started with Guardian.
Please check it out if you can and send us feedback if you have any difficulties.

Cheers,
@luan & @svett, CF Garden Team

**Comment by AdoHe** [comment]
@luan Thanks very much. I will push some code to guardian later.
