### ISSUE TITLE
can the network plugin action be a flag?

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry-incubator/guardian#16]
Hey there,

Any chance we can make the network plugin action (`up` vs `down`) into a flag?
e.g.

```
my-plugin --extra-arg=something --action=up --more-args=whatever
```

This would make it way easier to parse args in the plugin.

Currently, we have to do this:
https://github.com/cloudfoundry-incubator/guardian-cni-adapter/commit/21f9a6c9b0549216d528754f274b6e6bb70284f7

Thanks!

cc: @sykesm @zachgersh

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#113209203](https://www.pivotaltracker.com/story/show/113209203) can the network plugin action be a flag?


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by goonzoid** [comment]
Our Tracker/GitHub integration is broken at the moment, so closing this manually since it's now done :)
