### ISSUE TITLE
Use github.com/vishvananda/netlink to replace libcontainer/netlink

### ISSUE THREAD

**Issue by AdoHe** [cloudfoundry-incubator/guardian#2]
FYI. runc has just replaced libcontainer/netlink with vishvananda/netlink, which is better.

**Comment by julz** [comment]
Indeed, we're already using the vishvananda package in [new code here](https://github.com/cloudfoundry-incubator/guardian/blob/master/kawasaki/netns/netns_execer_linux.go#L8), but it's a good point that we're still using the old package in the code we've moved over from garden-linux. I've added [a chore](https://www.pivotaltracker.com/story/show/105656644) to our tracker to migrate over -- thanks much for noticing!

**Comment by AdoHe** [comment]
@julz I did notice this, I think we should use vishvananda/netlink to do bridge related configuration, we can avoid lock, and write more clean code. Besides I am learning your code, you did real amazing work :+1: , I will contribute some code if possible :)

**Comment by julz** [comment]
@AdoHe yeah I agree, I'd love to convert the old code over to the new library, and we'd very much welcome any contributions! Here's [the story we created from this issue](https://www.pivotaltracker.com/story/show/105656644) to upgrade to the new library.

**Comment by AdoHe** [comment]
@julz I will open a new pull request as soon as I can. Thx

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#109274888](https://www.pivotaltracker.com/story/show/109274888) Use github.com/vishvananda/netlink to replace libcontainer/netlink


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by svett** [comment]
FYI @AdoHe we replaced the netlink package with vishvananda's netlink library.
