### ISSUE TITLE
iptables setup issue

### ISSUE THREAD

**Issue by AdoHe** [cloudfoundry-incubator/guardian#5]
If I run the iptable setup script on Centos 7, I will get such error: `iptables: command not found`, the root cause is that `PATH` env wrong. Whether should we add path export at the beginning of setup script?

**Comment by goonzoid** [comment]
Hi @AdoHe we don't currently (officially) support CentOS but we'd be very happy indeed to accept a PR to do this... :)

**Comment by AdoHe** [comment]
@goonzoid Ok, I will open a PR if I find a good solution.
